### ISSUE TITLE
Wrong wasm_exec.js version

### ISSUE THREAD

**Issue by clementlefevre** [vsoch/regression-wasm#2]
First, thanks for this very nice demo !

By kicking the local build and starting the python http server, i got the following error in the Chrome Developer console :
*LinkError: WebAssembly.instantiate(): Import #1 module="go"*

I then just replace in the */docs* folder the  `wasm_exec.js` file the one matching my local Go version :
`cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./docs`

Works fine. 
Again, great demo.

**Comment by vsoch** [comment]
It's undoubtedly going to be the case that what you have locally might be different from what is needed - notably the current one still works on it's original gh-pages deploy -> https://vsoch.github.io/regression-wasm/. So if you have a suggestion for how to address this (a note in the README? A folder with other versions?) please open a PR with your suggestion, otherwise the issue here is not super useful to help future users. Thanks!

**Comment by clementlefevre** [comment]
Solved via https://github.com/vsoch/regression-wasm/pull/3

**Comment by vsoch** [comment]
Thank you!

I'm excited to see the space of wasm examples / technology improve - I haven't done it in a while and would like to find reasons to make more little apps / pages.
